# Generated by Django 2.0.4 on 2018-04-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter the name of the animal: ', max_length=60)),
                ('nickname', models.CharField(default='', help_text='Enter the nickname of the animal:', max_length=60)),
                ('sci_name', models.CharField(default='', help_text='Enter the scientific name of the animal:', max_length=100)),
                ('diet', models.CharField(blank=True, choices=[('C', 'Carnviore'), ('O', 'Omnivore'), ('H', 'Herbivore')], default='m', help_text="Pick the animal's diet.", max_length=1)),
                ('info', models.CharField(default='', help_text='Enter the animal information: ', max_length=500)),
                ('inter', models.CharField(default='', help_text='Enter the animal interaction information: ', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter the exhibit name', max_length=200)),
                ('description', models.CharField(default='', help_text='Enter the exhibit description: ', max_length=200)),
                ('is_exit', models.CharField(blank=True, choices=[('T', 'Yes'), ('F', 'No')], default='m', help_text='Is this exhibit an exit?', max_length=1)),
                ('neighbors', models.ManyToManyField(related_name='_exhibit_neighbors_+', to='applic.Exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the zoo', max_length=200)),
            ],
        ),
    ]
