# Generated by Django 2.0.4 on 2018-05-05 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter the name of the animal: ', max_length=60)),
                ('nickname', models.CharField(default='', help_text='Enter the nickname of the animal:', max_length=60)),
                ('sci_name', models.CharField(default='', help_text='Enter the scientific name of the animal:', max_length=100)),
                ('diet', models.CharField(blank=True, choices=[('C', 'Carnviore'), ('O', 'Omnivore'), ('H', 'Herbivore')], default='m', help_text="Pick the animal's diet.", max_length=1)),
                ('info', models.CharField(default='', help_text='Enter the animal information: ', max_length=500)),
                ('inter', models.CharField(default='', help_text='Enter the animal interaction information: ', max_length=500)),
                ('image_url', models.CharField(default='', help_text='Paste an image url', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Exhibit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='Enter the exhibit name', max_length=200)),
                ('description', models.CharField(default='', help_text='Enter the exhibit description: ', max_length=200)),
                ('is_exit', models.CharField(blank=True, choices=[('T', 'Yes'), ('F', 'No')], default='m', help_text='Is this exhibit an exit?', max_length=1)),
                ('animals', models.ManyToManyField(blank=True, help_text='Add animals to this exhibit', to='applic.Animal')),
                ('neighbors', models.ManyToManyField(blank=True, help_text="Pick this exhibit's neighbors", related_name='_exhibit_neighbors_+', to='applic.Exhibit')),
            ],
        ),
        migrations.CreateModel(
            name='Zoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of the zoo', max_length=200)),
                ('entrance1', models.ForeignKey(default='', help_text='Select the zoo entrance:', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entrance', to='applic.Exhibit')),
                ('exhibits', models.ManyToManyField(help_text='Select as many exhibits as you wish. Make sure you have an exit!', to='applic.Exhibit')),
            ],
        ),
    ]
