# Generated by Django 2.0.4 on 2018-04-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0002_auto_20180426_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibit',
            name='animals',
            field=models.ManyToManyField(help_text='Add animals to this exhibit', to='applic.Animal'),
        ),
        migrations.AlterField(
            model_name='exhibit',
            name='neighbors',
            field=models.CharField(default='', help_text="Enter ID's of neighbor exhibits, separated by commas. I.E. 1,2,3", max_length=2),
        ),
    ]
