# Generated by Django 2.0.4 on 2018-04-28 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0003_auto_20180428_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exhibit',
            name='neighbors',
            field=models.CharField(default='', help_text="Enter ID's of neighbor exhibits, separated by commas. I.E. 1,2,3", max_length=50),
        ),
    ]
