# Generated by Django 2.0.4 on 2018-04-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applic', '0004_auto_20180428_1156'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoo',
            name='exhibits',
            field=models.ManyToManyField(help_text='Select as many exhibits as you wish. Make sure you have an exit!', to='applic.Exhibit'),
        ),
    ]
